### ISSUE TITLE
[FEATURE] Add support for additional VRBangers sites

### ISSUE THREAD

**Issue by Mellified** [dvick/vrbdownres#1]
VRBangers has announced they will be pulling the download button from VRConk.com and VRBTrans.com soon. It would be great to add support for these sites to the extensions. Since those sites use the same template they should just work.

**Comment by dvick** [comment]
I have support for VR Conk implemented in my local working copy. I'd be happy to add support for VRB Trans as well. Looks like that can likely be handled in the exact same way as VR Bangers (VR Conk is slightly different, although in a fairly inconsequential way). Can you give me the output of `document.querySelector('.single-video-info__actions').outerHTML` in the developer console on a video page, while logged in, so I can verify?

Assuming downloads are also being removed from VRB Gay and Blow VR, if anyone wants to give me the output of the above JavaScript for those sites, I should be able to add support for those sites as well.

I will be holding off on actually releasing these changes until downloads are actually removed from these other sites. With the removal of downloads from all sites (again, assuming that is the case), I'd say it's even more likely they remove the underlying functionality to the download button, in which case there might be nothing I can really do.

**Comment by airo93** [comment]
Hey @dvick , BlowVR is getting same treatment.  There is a bit of discussion on this form if you wanted to check it out, this was about the VRBangers removal though - https://discuss.eroscripts.com/t/vrbangers-video-download-changes-june-2024/170257/1

That query selector didn't seem to work, I ran the command __NUXT__.state.videos.video.downLoadVideoListForFront

and going the following -
`[
    {
        "size": "0.71 GB",
        "quality": "2K_180x180_3dh",
        "label": "2K",
        "url": "..."
    },
    {
        "size": "1.63 GB",
        "quality": "3K_180x180_3dh",
        "label": "3K",
        "url": "..."
    },
    {
        "size": "2.97 GB",
        "quality": "4K_180x180_3dh",
        "label": "4K",
        "url": "..."
    },
    {
        "size": "3.37 GB",
        "quality": "5K_180x180_3dh",
        "label": "5K",
        "url": "..."
    },
    {
        "size": "4.03 GB",
        "quality": "6K_180x180_3dh",
        "label": "6K",
        "url": "..."
    },
    {
        "size": "6.68 GB",
        "quality": "8K_180x180_3dh",
        "label": "8K",
        "url": "..."
    }
]`

Note - replaced actual urls with '...'

**Comment by dvick** [comment]
@airo93 Good to know that `__NUXT__.state.videos.video.downLoadVideoListForFront` exists for Blow VR too, but that's not really what I'm looking for here. I'm surprised the JS I provided didn't work. It definitely works as expected when not logged in (but I do need the logged in result). Could you try right clicking the download button, clicking 'Inspect', and then switching to the console and running `$0.parentElement.parentElement.parentElement.outerHTML`? (That may or may not be an extra 'parentElement'. If you know what you're doing, you could of course just copy the HTML from the element inspector as well.)

**Comment by airo93** [comment]
> $0.parentElement.parentElement.parentElement.outerHTML
@dvick 
```
<div data-v-0fb6302e="" data-testid="element_003770" class="single-video-info__actions"><div data-v-5074a90a="" data-v-0fb6302e="" data-testid="element_000269" class="video-download-button app-menu --block"><div data-testid="element_000270" class="app-menu__activator"><button data-v-5074a90a="" type="button" data-testid="element_000056" class="video-download-button__activator app-link app-link--uppercase app-link__button app-link__button--block">
      Download
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25 24" fill="none" class="app-icon" data-v-67c9ab81="" data-v-5074a90a="" data-testid="" style="--icon-width: 24; --icon-height: 24;">
      <path d="M12.5 15L12.8536 15.3536L12.5 15.7071L12.1464 15.3536L12.5 15ZM18.8536 9.35355L12.8536 15.3536L12.1464 14.6464L18.1464 8.64645L18.8536 9.35355ZM12.1464 15.3536L6.14645 9.35355L6.85355 8.64645L12.8536 14.6464L12.1464 15.3536Z"></path>
    </svg></button></div> <!----></div></div>
```

The document.querySelector('.single-video-info__actions').outerHTML also works now, not sure why it didn't work the first time I tried it.

**Comment by dvick** [comment]
@airo93 Thanks. I have added support for Blow VR in the [test](/dvick/vrbdownres/tree/test) branch, and made it so it will add the button even when it already exists, for testing. Can you download the [source ZIP](/dvick/vrbdownres/archive/refs/heads/test.zip) from that branch and test it out? You should see two identical download buttons on Blow VR if it's working correctly.

**Comment by airo93** [comment]
> @airo93 Thanks. I have added support for Blow VR in the [test](/dvick/vrbdownres/tree/test) branch, and made it so it will add the button even when it already exists, for testing. Can you download the [source ZIP](/dvick/vrbdownres/archive/refs/heads/test.zip) from that branch and test it out? You should see two identical download buttons on Blow VR if it's working correctly.

I believe its working correctly, I do see 2 download buttons, the second just opens the regular button probably because their tied to the same script.

Also see the same 2 buttons on VRConk

**Comment by dvick** [comment]
Released v1.3 a few days ago adding support for VR Conk and Blow VR. Might still try to add support for the other two sites if someone wants it and can help me confirm functionality.

**Comment by Goonaholic** [comment]
I have a VBRTrans login and it also just had the downloads removed. Here is the output I got.
```
<div data-v-cdf33dc2="" data-testid="element_000672" class="single-video-info__actions"><div data-v-bccc8a02="" data-v-cdf33dc2="" data-testid="element_000269" class="video-download-button single-video-info__download-button app-menu --block"><div data-testid="element_000270" class="app-menu__activator"></div> <!----></div></div>
```

**Comment by dvick** [comment]
@Goonaholic Unfortunately, that's not as helpful with the button already removed, but I went ahead and added support for VRB Trans in the vrbtrans branch, making it work the same as for vrbangers.com. The button may or may not look exactly as it did before, but I think it should likely work. Can you test and confirm? https://github.com/dvick/vrbdownres/archive/refs/heads/vrbtrans.zip

**Comment by Goonaholic** [comment]
@dvick I have tested it and it fits right in and functions as it should just like the main site. For me the main site and trans site are identical except the color scheme which it does inherit correctly.

**Comment by dvick** [comment]
I think this should be working now for all sites, including VRB Gay, with version 2.0. Closing issue. Will re-open if it turns out to not be working on a site.
